### ISSUE TITLE
Fix Token Refresh

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#100]

**Comment by j-schumann** [comment]
Funktioniert auch in der neuen Variante mit nuxt/auth nicht wirklich gut, da refreshed von Haus aus nur vor einem Request, nicht jedoch wenn der User auf einer Seite bleibt und keine axios-Requests absetzt -> schlecht für die Socket-Verbindung.

Branch feat-collab enthält daher next-auth-auto-refresh (oder so), das ist zwar auch suboptimal, erfüllt aber erstmal den Zweck. Issue schliessen wenn das in den main/develop übernommen ist.
