### ISSUE TITLE
Categories hinzufügen in Thema Form und Antrag erstellen

### ISSUE THREAD

**Issue by TungSaysHelloToU** [HackingPolitics/hp-frontend#109]

**Comment by norbertrost** [comment]
Es sollen 10 Kategorien angeboten werden, die in der Übersetzung folgendermaßen benannt sind:

"buildingAndLiving": "Bauen & Wohnen",
"educationAndResearch": "Bildung & Forschung",
"energyAndSupply": "Energie & Versorgung",
"mobility": "Mobilität & Logistik",
"environmentAndClimate": "Stadtgrün & Stadtklima",
"participationAndGovernment": "Bürgerbeteiligung & Verwaltung",
"socialAndHealth": "Soziales & Gesundheit",
"economyAndResources": "Wirtschaft & Rohstoffe",
"artAndCulture": "Kunst & Kultur",
"other": "Sonstiges"

Derzeit heißen die Kategorien im Client noch anders und es sind zu wenige. Die Kategorien werden an verschiedenen Stellen benutzt (sowohl, was die Anzeige betrifft wie auch die Auswahl).

**Comment by philmuze** [comment]
fetche die Kategorien im Antrag nun vom Server
