### ISSUE TITLE
Unklarer Fehler "validate.general.tooShort" beim Registrieren

### ISSUE THREAD

**Issue by f-jacobi** [HackingPolitics/hp-frontend#146]
Ich möchte mich auf der Plattform registrieren.
Nach Eingabe aller Daten bekomme ich dir Fehlermeldung "validate.general.tooShort" ganz oben angezeigt, jedoch ohne, dass ein Feld hervorgehoben würde.
Passwort habe ich beliebig verlängert, daran kann es nicht liegen.

**Comment by f-jacobi** [comment]
![image](https://user-images.githubusercontent.com/6143433/123925467-394d9780-d98b-11eb-81a1-c6a4bf85af0b.png)

**Comment by f-jacobi** [comment]
![image](https://user-images.githubusercontent.com/6143433/123925565-54b8a280-d98b-11eb-9ace-4271fd3bf666.png)

**Comment by f-jacobi** [comment]
Beobachtung beim gemeinsamen Test 30.6.: vermutlich wird hier die Motivation validiert, die der Nutzer vorher angab (bei mir: "warum willst du bei dem Projekt mitmachen", da ich mich im Rahmen des "beim Projekt bewerben" registriere)

**Comment by philmuze** [comment]
@f-jacobi sollte geklärt sein mit #158
