### ISSUE TITLE
Projekt Anlegen: Seite 3 nicht benutzbar

### ISSUE THREAD

**Issue by j-schumann** [HackingPolitics/hp-frontend#152]
https://prnt.sc/17hagpt

Seite 3 ist mir unklar. Laut Pflichtenheft können normale Nutzer keine Stadträte (mehr) anlegen, sie müssen also einen schon bestehenden auswählen. 

* Warum sind hier Angaben zum Erstellen eines Stadtrats und die Auswahl eines bestehenden Rats gemischt?
* Wenn kein Rat verfügbar ist sollte eine Meldung kommen "Projektanlegen derzeit leider nicht möglich..." (Übersetzung für Norbert).
* Wenn ich einen auswähle und sonst nichts auf dieser Seite angebe dann macht "Projekt anlegen" zumindest ein API-Request, wenn das aber fehlschlägt (mein zuvor angegebener Titel ist zu kurz) zeigt er mir aber keinerlei Fehler an sondern macht einfach nix im Frontend.
* Hier und auch auf anderen Seiten steht etwas wie "Council ist ein Pflichtfeld." oder "Motivation muss 9 oder mehr Zeichen lang sein.", die Bezeichnungen in den Meldungen stimmen aber nicht mit dem Label des Felds überein, sind das Übersetzungen die Norbert anpassen kann? Ich hätte ja die Texte allgemein gehalten "Dies ist ein Pflichtfeld", "Bitte mindestens 9 Zeichen angeben" etc.

**Comment by philmuze** [comment]
habe das Formular heute überarbeitet, bitte mal checken

**Comment by j-schumann** [comment]
Ok, keine 3. Seite mehr, das passt erstmal.
