### ISSUE TITLE
Antragsprojekt erstellen

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#158]
### Schritt 1

- [x] Validierung checken
- [x] Bildupload verstecken

### Schritt 2

- [x] label, placeholder, help für Formulare
- [x] Ausgewählte Kategoriefarbe stärken
- [x] Kategorienamen ändern @norbertrost 
- [x] Kategorien von DB ziehen
- [x] motivation validation too short

### Schritt 3

- [x] Bezeichnung Formular (Parliaments)
- [x] nur Stadtrat wählen lassen, andere  Felder raus -> muss in Adminmaske
- [x] Auswahl Stadtrat auf Seite 1 und Schritt 3 raus

### Anfrage Login vs Registrieren

- [x] motivation validation kommt zu spät
- [ ] nach Erfolg muss Screen kommen mit "Projekt angelegt, Account aber bitte noch Email bestätigen."
- [x] Validierung Email im Backend rausnehmen

**Comment by philmuze** [comment]
@norbertrost @f-jacobi @ruebi hab heute einen Großteil hier umgesetzt bekommen

**Comment by norbertrost** [comment]
- [ ] #166: Abschluss des Projekt-anlegen-Prozesses fordert weiterhin Login/Registrierung, auch wenn ich eingeloggt bin
