### ISSUE TITLE
Setup API Core (from futureCityProjects)

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#16]

**Comment by j-schumann** [comment]
deployed: https://api-dev.hpo.vrok.de/

API Endpoints + schema coming

**Comment by j-schumann** [comment]
[HPO.zip](https://github.com/HackingPolitics/hp-frontend/files/6164594/HPO.zip)
Anbei ein Axios-basierender API-Client der funktioniert / funktionieren sollte ;)
Samt Definition der erwarteten Eingaben + Rückgaben.

Die API verwendet [Hydra](https://www.hydra-cg.com/spec/latest/core/) und das damit verbundene Format für die Rückgabe von Collections samt Paging und der Verlinkung von Entities.

**Comment by j-schumann** [comment]
Login: 
```ts
    const auth: IAuthReply = yield call(apiClient.requestAuthToken, action.credentials)
```

Logout: JWT aus dem State löschen / eigenes Cookie löschen, es verfällt dann selbst. Ebenso Refresh Token löschen.

Refresh des JWT (vor oder nach Ablauf desselben) mittels Refresh Token (vor Ablauf desselben ;-)):
```ts
    const newAuth: IAuthReply = yield call(apiClient.refreshAuthToken, refreshToken)
```
`yield call()`ist die Redux-Saga Syntax, muss in das client-spezifische Promise-/Async-Handling übersetzt werden.

JWT muss im Auth Header übergeben werden:

```ts
    apiClient.axios.interceptors.request.use((request: AxiosRequestConfig): AxiosRequestConfig => {
      // these endpoints do not work when an (expired) token is present in the headers
      if (request.url === "/authentication_token" || request.url === "/refresh_token") {
        return request
      }

      const token = selectAuthToken(store.getState())
      if (!token) {
        return request
      }

      request.headers = request.headers || {}
      request.headers.Authorization = `Bearer ${token}`

      return request
    })
```
