### ISSUE TITLE
Denkarbeit Formulare

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#162]
### Allgemein

- [x] Menuposition 3 und 4 tauschen
- [x] Klammer oder Button -> ausblenden

### Thema

- [x] Introtext unter Seitentitel (in allen Formularen)
- [ ] Submit Button anbieten
- [x] Kategorien ändern checken

### Probleme und Handlungsfelder

- [x] Initialer Start: Problem hinzufügen - Input danach anzeigen
- [x] Design checken (Highlight Drag and Drop)
- [ ] Buttons "Stichpunkte hinzufüge

![Screenshot 2021-06-30 at 11 04 45](https://user-images.githubusercontent.com/1415444/123933811-03141600-d993-11eb-872c-d70d45bd3705.png)

- [x] neue Probleme werden nicht angezeigt
- [x] Icon nach Drag und Drop raus

### Argumente und Gegenargumente

![Screenshot 2021-06-30 at 11 18 25](https://user-images.githubusercontent.com/1415444/123935903-f1cc0900-d994-11eb-87fe-ef7c520f9543.png)

### Fraktionen

![Screenshot 2021-06-30 at 11 28 19](https://user-images.githubusercontent.com/1415444/123937275-491ea900-d996-11eb-8529-63d720654560.png)

- Fraktionen anbinden
- Interessen

###  Strategie

- [x] Label umbenennen in Name der Organisation

**Comment by norbertrost** [comment]
Ergänzung zu "Antragsthema & Kategorie" (ehemals: "Thema"):

- [ ] bei "Antragsprojekt starten" wird zwischendurch die "Antragsidee" abgefragt. Diese muss beim "Thema" weitergenutzt werden, sonst macht es keinen Sinn, sie abzufragen. (Ich habe "Antragsidee" jetzt per Übersetzung anders verwendet, nämlich als "Ziel des Antrags". Sonst doppelt sich der Inhalt von "Antragsidee" mit "Antragstitel" oder "Antragsthema"

**Comment by norbertrost** [comment]
Im Screen "Problem & Handlungsauftrag" habe ich bei den Problemen Texte eingetragen, die etwas länger sind. Das Formular bleibt aber einzeilig (siehe Anhang). Daher sind Teile meiner Texte nicht sichtbar. Außerdem signalisiert das Formular mir nicht angemessen, dass ich es editieren kann, wenn ich den Text anklicke. Es kommt nur ein winziger lila Strich hinzu und der dünne Cursor, was beides zu wenig ist, um zu merken: "Ah, ich kann hier den Text editieren!" Daher:

- [ ] Text-Darstellung muss mehrzeilig erfolgen, um den gesamten eingegebene Text darzustellen
- [ ] eindeutige farbliche oder anderweitige Reaktion des Eingabeformulars, anhand derer ich sehe, dass ich im Editiermodus bin
- [ ] prüfen, ob dieses Problem auch bei anderen Eingabefeldern an anderen Stellen auftritt, z.B. bei den Argumenten und Gegenargumenten oder den Fraktions-
![Bildschirmfoto 2021-06-30 um 14 04 01](https://user-images.githubusercontent.com/60394582/123957822-8e4dd580-d9ac-11eb-9985-a6ad38f97d8d.png)
Eigeninteressen

**Comment by norbertrost** [comment]
- [ ] Eingabe des Themas (bei "Antragsthema und Kategorie" wird nicht übernommen: kein Button da, um es explizit zu speichern. Wechseln zu einem anderen der 5 Workflow-Schritte und Rückwechsel zeigt keine Änderung an: die ursprünglichen Daten sind weiter erhalten. -> vermutlich verbunden mit obigem Issue "Initialer Start: Problem hinzufügen, Input danach anzeigen"
- [ ] Der Button zum Hinzufügen von Problemen und Gegenargumenten ist jetzt rot auf lila. Nicht gut lesbar: es braucht mehr Kontrast!

**Comment by philmuze** [comment]
@norbertrost ich war hier noch NICHT dran. Es macht aktuell keinen Sinn das weiter zu testen. Ich gebe eine Rückmeldung.
