### ISSUE TITLE
"Problem" lässt sich zur Idee hinzufügen, obwohl Nutzer ausgeloggt ist

### ISSUE THREAD

**Issue by f-jacobi** [HackingPolitics/hp-frontend#163]
In aktueller Live-Umgebung wird der Nutzer ja nach wenigen Augenblicken ausgeloggt (bekanntes Token-Problem).

Ich habs getestet: im ersten Browserfenster blieb ich auf der "Probleme eingeben"-Seite; in einem anderen Browserfenster verifizierte ich, dass das Token abgelaufen ist. Dann fügte ich im ersten Fenster ein neues Problem hinzu. Nach neuem Login war das neu hinzugefügte Problem da - ich hatte also trotz abgelaufenen Tokens Schreibrechte im Projekt

**Comment by j-schumann** [comment]
Das halte ich für ausgeschlossen, das ist unit-tested: https://github.com/HackingPolitics/hp-backend/blob/main/tests/Api/ProblemApiTest.php#L119

Ich denke eher du hattest in dem 2. Tab noch ein gültiges Token. Die Tabs müssen nicht zwingend das gleiche Token verwenden, wie Philipp das im einzelnen implementiert hat kann er dir sagen.

**Comment by f-jacobi** [comment]
Ok, dann gerne schließen. Hätte mich auch gewundert! ;)

Am Mi., 30. Juni 2021 um 11:40 Uhr schrieb j-schumann <
***@***.***>:
