### ISSUE TITLE
"Antragsprojekt starten": Fordert Login, obwohl ich eingeloggt bin

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#166]
Ich habe die drei Schritte von "Antragsprojekt starten" durchlaufen.
Wenn ich nicht eingeloggt war, läßt mich die Software das nicht abschließen, liefert aber auch keine Fehlermeldung.
Wenn ich eingeloggt war, werde ich beim Abschluss aufgefordert, mich zu registrieren oder einzuloggen.

**Comment by j-schumann** [comment]
Wenn ich ausgeloggt ein Projekt anlegen will, die Option "einloggen" wähle und das dann tue (mit einem Passwort Fehlversuch), bin ich zwar eingeloggt aber erhalte keinen Hinweis das etwas angelegt wurde und in der Datenbank ist auch nichts da. (Leider vergessen in die Netzwerkkonsole zu schauen ob da ein fehlgeschlagenes API-Request drin ist. Aber wenn da eins wäre sollte ich auch einen Fehler angezeigt bekommen ;) )

**Comment by philmuze** [comment]
Gerade getestet, eingeloggt, Projekt erstellt, Porjekt da und auch editierbar.

**Comment by philmuze** [comment]
Brauch hier mehr Input (Videos, Console Logs, etc)

**Comment by norbertrost** [comment]
Okay: Habe Shift Reload auf der Testplattform gemacht und den Vorgang erneut durchprobiert. Jetzt geht es. Bei "Meine Anträge" sind auch alle Anträge da, und der Klick auf sie ist möglich und die dahinterliegenden Workflow-Schritte sind anklickbar und nutzbar.

Keine Ahnung, was das heute morgen war, vielleicht lag da noch was Altes im Cache.

Jakobs Fehlermeldung (siehe oben) will ich aber nochmal ergänzen um:
- [ ] Nach Login lande ich auf der allgemeinen Übersicht. Die Umleitung sollte mich aber idealerweise direkt zum Workflow des neu entstandenen Antrags führen, also zu https://testing.hacking-politics.de/antraege/61

**Comment by philmuze** [comment]
@norbertrost bitte nicht einfach ergänzen. Neues Thema = neues Ticket. Macht es einfacher mit dem Überlick. Danke.
