### ISSUE TITLE
Logout + Redirects/Fehler Antragsseite

### ISSUE THREAD

**Issue by j-schumann** [HackingPolitics/hp-frontend#169]
Eingeloggt, Antragsseite aufgerufen, Logout angeklickt:

- [x] ich sollte umgeleitet werden zum Login oder zur Startseite, bleibe aber auf der Projektseite?

- [x]  F5 leitet mich auch nicht um sondern führt das API-Request für's Projekt aus? Sollte 404 oder 403 anzeigen:
https://prnt.sc/17oljrj

- [x]  Aufruf (eingeloggt) einer beliebigen Antrags-URL (bspw 127.0.0.1:3000/antraege/200) zeigt weder 404 noch 403?

**Comment by philmuze** [comment]
hab ich auf https://testing.hacking-politics.de/ zum Testen drin
