### ISSUE TITLE
SMTP für Mailversand

### ISSUE THREAD

**Issue by j-schumann** [HackingPolitics/hp-frontend#172]
Bitte Zugangsdaten für einen SMTP-Zugang für den Mailversand der Live-Umgebung bereitstellen, no-reply@hp.de oder soetwas.

**Comment by philmuze** [comment]
@j-schumann  angelegt https://hackingpoliticsgroup.slack.com/archives/C01GPKM1V8S/p1625229055002900?thread_ts=1625217601.000300&cid=C01GPKM1V8S

**Comment by j-schumann** [comment]
Eingerichtet, läuft
