### ISSUE TITLE
Kategorienamen übersetzbar machen

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#181]
Die Kategorien sind aktuell nicht mehr über die Sprachdatei übersetzbar. Der Abschnitt ist rausgeflogen. Ticket #158 soll ich die Übersetzung machen. Würde ich gern, dafür brauche ich keys. Außerdem muss die Kategorieliste dort, wo sie benutzt wird (mindestens: Antragsprojekt erstellen, Workflow: Thema dieses Antragsprojekts) mit den übersetzten keys arbeiten - noch ist die Liste offenbar zu kurz.

  "repeatable": {
    "category": {
      "buildingAndLiving": "Bauen & Wohnen",
      "educationAndResearch": "Bildung & Forschung",
      "energyAndSupply": "Energie & Versorgung",
      "mobility": "Mobilität & Logistik",
      "environmentAndClimate": "Stadtgrün & Stadtklima",
      "participationAndGovernment": "Bürgerbeteiligung & Verwaltung",
      "socialAndHealth": "Soziales & Gesundheit",
      "economyAndResources": "Wirtschaft & Rohstoffe",
      "artAndCulture": "Kunst & Kultur",
      "other": "Sonstiges"
    }
  },

**Comment by philmuze** [comment]
@norbertrost Kategorien kommen wie gesagt aus der DB. Du wirst diese morgen im Adminbereich bearbeiten können. Sie werden nicht mehr über die lang Files übersetzen.

**Comment by philmuze** [comment]
@norbertrost Kategorien sind im Adminbereich nun editierbar

**Comment by norbertrost** [comment]
Funktioniert: Anlegen, ändern, löschen.
Closed.
