### ISSUE TITLE
Frisch angelegtes Projekt erscheint nicht in "meine Anträge", Workflow nicht editierbar

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#182]
Habe ein neues Antragsprojekt angelegt, werde nach dem Login auch dorthin weitergeleitet.
Aber:

- [ ] keine Kachel des Workflows war anklickbar: es ist also keine Weiterbearbeitung des Projekts möglich
- [ ] in der Übersicht "meine Anträge" taucht es nicht auf: nur andere Antragsprojekte sind vorhanden, während die Plattform links im "Userprofil" sagt: "0 Anträge". (#159 ?)

**Comment by philmuze** [comment]
@norbertrost bekomme den Bug nicht reproduziert. War ausgeloggt, habe ein neues Projekt angelegt, habe mich eingeloggt, Projekt erscheint und ist editierbar. Kannst du mir ein Video machen oder es mir live zeigen?

**Comment by norbertrost** [comment]
Kann ich auch nicht mehr reproduzieren. Aktuell scheint das gut zu gehen. Einziges Problem: neuer Antrag ist doppelt vorhanden (#195 )

Close?
