### ISSUE TITLE
PUT for /fractions/id change data structure in project response - only for active flag

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#192]
After an update of the active status via PUT in fractions the data structure in the project response is changed to fractions as an object not an array like before. 

![screen](https://user-images.githubusercontent.com/1415444/124722264-2e09e700-df0a-11eb-98d6-cd7e47a8fd17.png)

**Comment by j-schumann** [comment]
Screenshot is after the PUT? Do you have an example output from before the request?
Screenshot shows a council output but issue mentions "project response"?

**Comment by philmuze** [comment]
Sorry bug is in council response. Project response looks good.

**Comment by j-schumann** [comment]
fixed in stage.

* Inactive fractions aren't returned in council responses, only for PROCESS_MANAGER
* fraction data is now included in the project response (but without updatedAt/updatedBy)
