### ISSUE TITLE
Antragstitel und Antragsziel

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#194]
- [x] bei "Antragsprojekt starten" wird zwischendurch die "Antragsidee" abgefragt. Diese muss beim "Thema" weitergenutzt werden, sonst macht es keinen Sinn, sie abzufragen. (Ich habe "Antragsidee" jetzt per Übersetzung anders verwendet, nämlich als "Ziel des Antrags". Sonst doppelt sich der Inhalt von "Antragsidee" mit "Antragstitel" oder "Antragsthema"
- [x] das gleiche gilt für den Antragstitel: auch dieser muss beim "Thema" erneut mit aufgegriffen werden: durch ein editierbares Feld

**Comment by philmuze** [comment]
@norbertrost ist ergänzt bitte Texte ändern

**Comment by norbertrost** [comment]
Texte ergänzt.

**Comment by philmuze** [comment]
gemerged

**Comment by norbertrost** [comment]
Ein Translation-Key wird vermutlich falsch verwendet auf
https://testing.hacking-politics.de/antraege/2/thema

Vermutlich wird forms.topic.mainTopicSubtitle zweimal benutzt, dabei muss bei dem Titel-Eingabefeld forms.topic.mainTitleSubtitle benutzt werden.
