### ISSUE TITLE
Antragsthema wird nicht immer übernommen, neues Antragsprojekt doppelt vorhanden

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#195]
- [ ] #209
- [x] ich bin ziemlich sicher, beim Anlegen des neuen Projekts (Desire Z) auch Kategorien im Anlegeprozess angegeben zu haben. Diese wurden aber nicht übernommen.
- [x] das Projekt "Desire Z" ist doppelt vorhanden, obwohl ich es nur einmal eingetragen habe: https://testing.hacking-politics.de/antraege/79/ , https://testing.hacking-politics.de/antraege/78/

**Comment by ruebi** [comment]
- [ ] bei mir tritt ebenfalls der Fall auf, dass zwei Projekte mit gleichem Titel entstanden sind, statt einem. Vermutung: Norbert hat zum Zeitpunkt eine Aktion am Projekt vorgenommen (Mitglied Bewerbung). 
![image](https://user-images.githubusercontent.com/80104830/124772531-69250e00-df3c-11eb-88e2-d7c92f79f3f0.png)

**Comment by ruebi** [comment]
- [ ] wie bei Norbert: nicht alle im "Antrag erstellen" Prozess eingegebenen Daten werden in die Denkarbeit übernommen.
![FireShot Capture 432 - HackingPolitics Client - testing hacking-politics de](https://user-images.githubusercontent.com/80104830/124776959-282ef880-df40-11eb-99d5-4bfe4f6e7830.png)

**Comment by philmuze** [comment]
Doppeltes Projekt wird im Workflow ausgeloggt -> Projekt erstellen -> Einloggen angelegt, checken!
