### ISSUE TITLE
Handlungsauftrag fehlt

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#196]
Im Screen Problem und Handlungsauftrag fehlt der Handlungsauftrag:
Aktuell kann der User nicht sagen, was die Verwaltung eigentlich tun soll:
https://testing.hacking-politics.de/antraege/79/problem

**Comment by philmuze** [comment]
@norbertrost ist ergänzt bitte Strings anpassen

**Comment by norbertrost** [comment]
Technische Frage, @philmuze : Pull der de.json bringt keine Datei, in der dieser language-key drin ist. Ich nehme an, das hat mit dem branch "lang" zu tun. In dem arbeite ich, du ja aber nicht. Wie komme ich an die aktualisierte de.json?

**Comment by norbertrost** [comment]
PS: es ist für die Übersetzung immer besser, wenn einfach der key unübersetzt an der Stelle zu sehen ist, wo er ebenausgegeben wird. Dann kann ich auch übersetzen, ohne dass der key schon in der language-Datei drin sein muss, weil ich ihn einfach nachpflege.

**Comment by philmuze** [comment]
@norbertrost ist jetzt drin. ich schaue mir so immer an ob der key auch greift.

**Comment by norbertrost** [comment]
Vorhanden. Übersetzt. Closed.
