### ISSUE TITLE
Fraktionsinteressen: Editieren geht nicht, Übersetzbarkeit/Selbsterklärung

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#199]
- [x] Das Hinzufügen von Fraktionsinteressen geht, das Editieren aber nicht: es fehlt erneut ein "absenden"-Button o.ä. Edits gehen verloren.
- [x] der Text "Noch x Stimmen für ein mehrheitliches Interesse" ist nicht übersetzbar. Ich muss das aber verständlicher formulieren.
- [x] auch die anderen Inhalte in dem Screen sind nicht übersetzbar. Braucht es aber, um die Selbsterklärungsfähigkeit des Screens zu erhöhen.
- [ ] Was der Schalter zum Auswählen einer Fraktion bedeutet ist nicht klar. Ursprüngliche Funktion: "Als Partner für diesen Antrag denkbar?" Die Schalter-Funktion muss textlich erläuterbar sein.

**Comment by ruebi** [comment]
@norbertrost der Optimierungsidee zum Toggle-Button mit dem zusätzlichen Hinweistext kann ich nicht zustimmen.
Man könnte aber statt "<x> Partnerstimmen" --> "<x> Partnerstimmen ausgewählt" formulieren. So weiß der Nutzer, dass er diese Zahl modellieren kann. (dass das über die Toggle Buttons funktioniert ergibt sich aus dem inhaltlichen Kontext der Liste und der Lust, daran rumzuspielen und zu gucken was passiert).

**Comment by norbertrost** [comment]
@ruebi : Übersetzungsvorschlag habe ich mal so übernommen. Ja, macht das ganze etwas zugänglicher. Dennoch finde ich, dass beim Betreten einer jungfräulichen Seite die Schalter extrem dezent sind. Anklicken wollte ich da eher den Chart. Der User wird nicht gut geführt.

**Comment by ruebi** [comment]
Entscheidend zum Verständnis ist aus meiner Sicht, dass ausgewählte Fraktionen auf Anhieb im Überblick sind und im gleichen Moment der grünen Summe zugeordnet werden. Das tun sie auf aktuelle Weise besonders gut, bzw. dann mit textlicher Optimierung.

**Comment by philmuze** [comment]
Übersetzung und Update ist drin

**Comment by norbertrost** [comment]
Texte angepasst. Nach einem Update der Testplattform Bitte an @ruebi: Bitte nochmal Selbsterklärungsfähigkeit des Screens kritisch beleuchten.
