### ISSUE TITLE
Einführungstexte auf jedem Screen ermöglichen

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#200]
Ich brauche in jedem Workflow-Screen unter der Überschrift einen screen-spezifischen übersetzbaren Einführungstext. Ohne diesen Einführungstext ist der Screen nicht selbsterklärend, ohne Selbsterklärung wird er nur begrenzt verständlich.

**Comment by philmuze** [comment]
@norbertrost ist ergänzt bitte Texte anpassen

**Comment by norbertrost** [comment]
Texte hinzugefügt. Muss es mal live sehen.

**Comment by philmuze** [comment]
gemerged

**Comment by norbertrost** [comment]
Cool. Habe nochmal kleinere Änderungen gemacht. Ein weiterer Merge wäre schön.
