### ISSUE TITLE
Hocuspocus - Demo

### ISSUE THREAD

**Issue by j-schumann** [HackingPolitics/hp-frontend#206]
Ich habe in feat-collab das einmal umgesetzt und dazu den hp-socketserver angepasst. Dessen neue Version läuft nun auch unter socket-dev.hpo.vrok.de und socket-stage.hpo.vrok.de

* Custom Hocuspocus-Server als Backend-Bridge, erwartet das JWT im ersten Request und weitere Nachrichten mit dem erneuerten Token, disconnected den User wenn entweder das Token abläuft oder er laut Token nicht berechtigt ist für den angefragten Projekt-Raum
* Client nutzt einen angepassten Hocuspocus-Provider der eine custom TokenUpdateMessage unterstützt, kann sich mit dem neuen Server verbinden & Token updaten, anträge/[id]/schreiben synced einen Demo-Tiptap mit der Description des Projekts und zeigt einen Button der das Sperren/entsperren eines Formular simuliert (sync eines Booleans)
* nutzt nuxt-auth-auto-refresh (o.ä.) um das Token im Hintergrund auch ohne axios-requests zu refreshen

Todo:
* [ ] PM: Testen. Funktionierte bei mir gut mit 2 Usern, einer davon mit 2 Tabs, zeigt die Cursor an, speichert im Hintergrund mit dem zuletzt ändernden User die Daten im Backend
* [ ] PM: Code in den develop übernehmen
* [ ] PM: Struktur designen die abbildet welche Meta-Daten gesynced werden sollen (welche Forms / Felder sind von wem gesperrt)
* [ ] PM: Die UserListe die der Hocuspocus synced enthält alle WS-Clients, also auch einen User mehrfach wenn er mehrere Tabs offen hat, die Liste also entsprechend filtern und ggf. sicherstellen dass der User immer die gleiche Farbe zugewiesen kriegt
* [ ] PM: Den Provider aus dem Editor lösen, er muss ja dauerhaft irgendwo aktiv sein damit er für mehrere Seiten die aktiven User und Form-Locks anzeigen kann
* [ ] PM: Den setTimeout ersetzen der auf geändertes Token prüft durch einen watcher/eventListener der triggert wenn sich das Token in $auth ändert
* [ ] JS: Getrennte Räume für Daten + Meta-Daten, damit nicht bei Meta-Daten-Änderung auch ein Sync ans Backend ausgelöst wird obwohl sich nix geändert hat
* [ ] PM: Issues bei Hocuspocus eröffnen entsprechend #177, primär dazu das bei Disconnect vom WS-Server und erneuter Verbindung der Inhalt doppelt im Editor auftaucht, aber dann nur eine Instanz davon mit dem Server synced

**Comment by philmuze** [comment]
![Screenshot 2021-07-15 at 10 46 49](https://user-images.githubusercontent.com/1415444/125762485-88d2c77b-aef8-47f2-bfd2-92d2d7b163db.png)

@j-schumann in diese Richtung ☝

**Comment by j-schumann** [comment]
Okay, gut. Und bei welchen konrekten Feldern & Entitäten möchtest du live mitverfolgen was derjenige tippt der das Feld / Form gesperrt hat und bei welchen reicht es aus wenn sich der Client irgendwann mal von der API den Komplettstand holt?

**Comment by j-schumann** [comment]
Tja, ist inzwischen bisschen anders, habe eine andere Variante gefunden um das Syncen einfach abzubilden:
mit dem Awareness-State vom Hocuspocus, dort setzt du einfach bei jedem User ein Property das angibt in welchem Bereich er ist, ein Property welches Feld er gerade sperrt und gut ist, wird automatisch gesynct, der Client kann selbst entscheiden wann er einen anderen rausschmeisst und selbst locked (bspw. nach X min Inaktivität). Alles als Demo schon funktional in feat-collab, du musst nur noch verschieben an die richtigen Stellen, die weiteren Editoren dazubauen und eben Locking + Anzeige clientseitig einbauen.

Für die gesperrten Felder: Norbert hat zugestimmt dass es erstmal nicht nötig ist den anderen in Echtzeit beim Tippen zuzusehen wenn sie ausserhalb des Antragstextes arbeiten, ist daher nicht drin. Sinnvollerweise setzt du daher im Awareness noch einen weiteren State "projectSaved" o.ä. mit dem Zeitstempel wann der lokale Client an die API gepushed hat seine Änderungen (nur die geänderten Felder!) und prüfst dann in den anderen Clients bei Awareness-Update: Hat ein anderer einen größeren projectSaved als ich? Wenn ja dann lade das Projekt von der API neu (debounce!) und zeige die neuen Inhalte an, ohne dem User das Feld wegzukicken das er gerade bearbeitet. Und natürlich auch ohne die Proposal-Editor-Inhalte zu ersetzen, die werden ja über den WS gesynced+gespeichert.

Können dann einen Jitisi-Temrin machen und das mal durchgehen, mach einfach einen Terminvorschlag.
