### ISSUE TITLE
Textliche Überforderung Formularfelder

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#207]
![Screenshot 2021-07-07 at 18 12 22](https://user-images.githubusercontent.com/1415444/124794173-08530100-df4f-11eb-8fad-6ee290754c2c.png)

Ich empfinde die Formularfelder als Textwüste. Sowohl das Label als auch der Placeholder sind textlich ausgereizt. Denke, wenn wir soviel Text brauchen haben wir ein Problem, dass nicht klar wird was man hier eingeben soll.

Erbitte Einschätzung @ruebi und eventuelle Anpassung mit @norbertrost

**Comment by norbertrost** [comment]
Du willst Textwüste?
Dann probier's mal hiermit. Ist eine Anwendung zum gleichen Thema:
https://www.revosax.sachsen.de/vorschrift/2754-Saechsische-Gemeindeordnung :)

Davon hat der Hersteller noch gut 2500 mehr Module rumliegen.

Wir brauchen Selbsterklärung. Die politische Bildung in diesem Land ist so unterirdisch, dass der normale Bürger, an den sich die Plattform wendet, ungefähr Null Grundkenntnisse hat. Diese Lücke zu überbrücken wird ohne Hinleitungen und Anweisungen nicht gehen, es sei denn man geht entweder davon aus, dass immer jemand neben dem User sitzt, oder indem die Usability nochmal drei Faktoren zulegt und grafisch unterfüttert wird. So lange wir sowas nicht haben, was bleibt uns dann, die Punkte zu erklären?

Zuletzt:
Wenn die OpenSource steht kannst du ja alle Übersetzungsstrings mit eigenen Übersetzungen füllen, bis hin zu: "". So lange ich am Samstag 10 Gruppen gleichzeitig anleiten muss, brauche ich Unterstützung durch die Plattform, weil niemand in 10 breakout-rooms gleichzeitig sein kann.

So schaue ich jedenfalls da drauf.

**Comment by ruebi** [comment]
@philmuze @norbertrost Geht mir auch so!
Ich sehe hier folgende Situation der Erstnutzung - 
Der Nutzer will abchecken, was so alles für Funktionen in einem Projekt stecken und was für Aufgaben perspektivisch auf ihn und ein Team zukommen. Die Entdeckungsneugier wird aktuell ausgebremst. Es sind viele Inputs, die noch dazu verpflichtend sind. Für den initialen Schritt des Antrags sollte man dem Nutzer keine unnötigen Hürden einbauen.
Das hat erstmal nichts mit der Sinnhaftigkeit der Fragen zu tun, die sind sehr wertvoll fürs Teamverständnis. Aber der Zeitpunkt und die "Pflichtfeld" Sache finde ich unpassend. 
Im Bewerbungsprozess werden die Fragen ebenfalls gestellt. Dort machen sie inhaltlich mehr Sinn, überfordern den Nutzer nicht und es ist nachvollziehbarer, was mit den Daten passiert und wofür sie abgefragt werden.

Vorschlag:
**A) Wir reduzieren die Seite auf "Thema Eingrenzung" und "Kategorien".**
"Projekt-Gründer" müssen diese Angaben nicht machen, da allein ihre Initiative schon von Motivation und Engagement zeugt. Ob die Angaben zur Motivation nochmal irgendwo von irgendwem gelesen werden, ist aus meiner Sicht gerade unwichtig.

**B) Tooltips**
Was du "Selbsterklärung" nennst, Norbert. ist meistens eine Einzelfallentscheidung. Dafür sollte es konkreter werden: Selbsterklärung von was genau? Welchem Verständnis genau? Was muss in welchem Moment selbsterklärend sein?
Eine textliche Erklärbär-Lösung ist meiner Erfahrung nach immer die letzte Wahl. Eine gut gestellte Frage ist selbsterklärend. Wenn sie es nicht ist, hat sie nicht die richtige Sprache gefunden. 
Lösung: Zu jeder Frage kann es einen Untertitel geben (ist tlw. schon eingebaut). Hier aber die Zeichenlänge begrenzen! Alles was über die schnell erfassbare Variante hinausgeht, in Tooltips packen. Das betrifft aus meiner Sicht spezielle erklärungsbedürftige Begriffe oder ein Vorwissen zu einer Frage, das man erst aufbauen muss.

Wichtiges Thema! Ich bin anfangs für "weniger ist mehr" und erst nach richtigen Nutzertests gezielt schauen, wo tatsächlich Verständnislücken auftauchen.

**Comment by norbertrost** [comment]
Darf ich daran erinnern, dass ihr es wart, die das Zusatzfeld, das jetzt hier "Ziel" heißt, angefordert hattet? :)

Könnt ihr mir bitte den Gefallen tun und euch nun ausgerechnet daran NACH dem Workshop austoben?
Ich stehe an der Front: ich habe den Workshop gegenüber der Anstiftung eingetütet, sehe mich denen gegenüber in der Pflicht und den Teilnehmern auch. Dinge, die nicht funktionieren, werden primär mir zugeschrieben. Niemand sonst hält seinen Namen und sein Gesicht hin.

Es gibt viel wichtigere Issues, die hier noch rumliegen, die die tatsächliche Funktionalität, Bedienbarkeit und Selbsterklärung betreffen. Ich bitte darum, ausgerechnet das hier bis Sonntag so zu lassen, danach könnt ihr meinetwegen machen, was ihr wollt.
