### ISSUE TITLE
Projektbild aus Unsplash wählen lassen

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#212]
- [x] Property für Projekt hinzufügen @j-schumann 
- [x] Bildwähler im Schritt 1 einbauen

**Comment by philmuze** [comment]
@ruebi ich habe mich mal an einem kleinen Bildwähler für das Projekt versucht und dabei Unsplash genutzt. Was denkst du? 

https://user-images.githubusercontent.com/1415444/124913842-e8bfe500-dfef-11eb-8d36-fb1b16aaecef.mp4

**Comment by j-schumann** [comment]
done, deployed @stage

**Comment by ruebi** [comment]
@philmuze sieht ja toll aus! Cooles Feature. Finde die Palette an Bildern auch passend.

**Comment by norbertrost** [comment]
Jo, das teile ich: ist eine sehr nützliche Funktion. Bin überrascht, dass es sowas gibt. Finde ich super.
Rechtliche Fragen (Copyright, Nutzungsrechte usw.) scheinen geklärt: https://unsplash.com/license
Wie verhält sich diese Einbindung externer Ressourcen beim Ausfall des Bildlieferanten? Werden die Bilder lokal gespeichert und dann trotzdem angezeigt? Oder fällt dann die Plattform aus, weil die Ressourcen nicht nachgeladen werden?

Ich finde die Bildauswahl etwas schwer zugänglich. Nur in der Workflow-Übersicht in einem kleinen separaten Icon scheint diese Auswahl möglich zu sein. Brauchen wir einen 6sten Punkt für die Denkarbeit, sowas wie "Meta-Daten zum Antragsprojekt"?
