### ISSUE TITLE
"Wirkung auf's Problem" fehlt

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#213]
Das Arbeitsblatt und daher auch das Pflichtenheft sehen im Screen "Problem & Handlungsauftrag" eigentlich noch ein Textfeld "Wirkung auf's Problem" vor. Damit reflektieren die User, inwieweit die angegebenen Handlungsaufträge tatsächlich auf die vorgegebenen Probleme wirken. Dies verhindert im Denkprozess, dass man **vermeintlich lösungsorientierte** Handlungsaufforderungen benennt, die bei näherer Betrachtung am zuvor definierten Problem vorbeigehen.
In politischen Diskursen und Wunschkonzerten passiert das oft: es werden Probleme benannt, die durch die dann vorgeschlagenen "Lösungen" gar nicht adressiert werden.

Daher möchte ich anregen, dieses Textfeld nachzupflegen. (Ich gehe davon aus, dass die API entsprechend vorbereitet ist.)

**Comment by philmuze** [comment]
added

**Comment by norbertrost** [comment]
Absenden/Speicher-Button fehlt. Texteingabe kann nicht "abgeschlossen" werden.

**Comment by philmuze** [comment]
stimmt nicht ganz. sobald das Formularfeld verlassen wird speichert es. Ein Pattern dass wir uns am Wochenende mal anschauen und danach bewerten, siehe #209 cc @ruebi

**Comment by norbertrost** [comment]
Feld vorhanden. "Speichern"-Usability wird abseits dieses Tickets behandelt.
