### ISSUE TITLE
Meine Anträge: leer

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#214]
Beim Testen das seltsame Verhalten, dass die Übersicht "meine Anträge" manchmal leer ist und manchmal nicht.
Aktueller Reproduktionsweg:
Drücke ich reload auf
https://testing.hacking-politics.de/antraege
-> "keine Anträge vorhanden"
Gehe ich über "Alle Antragsprojekte" auf den öffentlichen Projektmarkt und dann über "Meine Anträge" wieder zu meinen Anträgen, werden sie angezeigt. Drücke ich reload: "Keine Antragsprojekte vorhanden"

Die Javascript-Konsole sagt:

90da32e.js:1 TypeError: Cannot read property 'map' of undefined
    at 90da32e.js:1
    at v (5ef5599.js:2)
    at Generator._invoke (5ef5599.js:2)
    at Generator.next (5ef5599.js:2)
    at r (5ef5599.js:2)
    at l (5ef5599.js:2)
    at 5ef5599.js:2
    at new Promise (<anonymous>)
    at 5ef5599.js:2
    at 90da32e.js:1

**Comment by philmuze** [comment]
fixed

**Comment by norbertrost** [comment]
Nee, irgendwas haut immer noch nicht hin:
Mir werden bei "Meine Anträge" alle 15 angezeigt, während links steht, ich sei nur bei 4 dabei. Das Paging untendrunter ist auch ziemlich verquer: viele zusätzliche Seiten, auf denen die Projekte sich teilweise (aber nicht immer) doppeln.

**Comment by philmuze** [comment]
jop hab den Query verhauen, sollte jetzt passen

**Comment by norbertrost** [comment]
Jo, jetzt schaut es gut aus! Cool. Close.
