### ISSUE TITLE
Footer: in die Seite integrieren?

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#215]
Super, dass die PTF- und BMBF-Logos ergänzt sind.
Allerdings macht das den Footer ziemlich dick. Da er nicht in die Seite integriert ist, sondern "drüber" liegt, ist er jederzeit zu sehen und nimmt viel Raum ein: ca. 20% des Bildschirms bei mir.
Aus Usability-Perspektive finde ich das zuviel: 1/5 des Screens für "toten Raum", mit dem ich als User nicht interagiere.

Daher der Vorschlag:

- [x] Footer lieber ans Ende jeder Seite integrieren statt "drüberlegen".

**Comment by norbertrost** [comment]
Ich sehe grade: der Footer wird ja gar nicht bei allen Seiten gleich behandelt. Bei den Workflow-Screens ist er ja bereits in die Seite integriert, bei allen anderen Seiten (inklusive der Workflow-Übersicht) scheint er "drüber" zu liegen. Ich bin ein wenig irritiert ;-)

**Comment by j-schumann** [comment]
Ich finde auch dass der Footer ziemlich groß ist und auch nicht fixed sein muss.
Bei mir sieht das im Normalbetrieb so aus: https://prnt.sc/19j79q3
Wenn ich weiter runter skaliere dann kann ich einzelne Elemente wie beispielsweise die Pagination nicht mehr (gut) lesen.
DIe Logos müssen nicht in der Software enthalten sein, nur in "Veröffentlichungen" (auch wenn die Webseite eine Art Veröffentlichung ist), hatte da schon mal beim PTF / DLR nachgefragt. Wäre gut wenn die auf der noch zu erstellenden - weil rechtlich erforderlichen - Impressumsseite unterkommen, oder eben in einem Footer der nicht fixed ist ;)

Ich nehme an auch die unnötige horizontale Scrollbar die er bei mir anzeigt hängt mit dem Footer zusammen.

**Comment by philmuze** [comment]
fixed

**Comment by norbertrost** [comment]
Fein!
