### ISSUE TITLE
Rechte auf Projektzugriff nicht eindeutig / "Meine Anträge" nicht korrekt

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#216]
Ich teste auf:
https://testing.hacking-politics.de/
mit dem User "norbert".
Ich habe 4 Anträge in "meine Anträge".
Zu diesen gehören die beiden folgenden nicht, aber dennoch habe ich unterschiedliche Nutzungsrechte:
- https://testing.hacking-politics.de/antraege/1 : ich kann dieses Projekt (vom öffentlichen Projektmarkt aus kommend) einsehen und es verändern. In der Mitgliederliste bin ich aufgeführt, aber das Projekt wird NICHT in "meine Anträge" aufgelistet
- https://testing.hacking-politics.de/antraege/8 : ich kann in diesem Projekt nichts verändern, nur einsehen

Ich vermute, dass die Rechte schon richtig gesetzt sind (weil ich in Projekt 1 offenbar Mitglied bin), dass aber "meine Anträge" nicht alles anzeigt.

Ich lege das erstmal Jakob hin, mit der Bitte, die API zu prüfen, ob die für "meine Anträge" alles richtig liefert. Falls ja, bitte zu Philipp weiterreichen, für Prüfung des Clients.

**Comment by j-schumann** [comment]
Die API ist unit-tested, da stimmt alles. Wenn du da etwas schreiben kannst was du nicht solltest dann weil Philipp es dir erlaubt und du gleichzeitig PM bist. Oder es sieht nur so aus als ob du schreiben könntest weil das Formular da ist, aber gespeichert wird zumindest in der API nichts.

Du bist Mitglied bei folgenden Projekten (erste Spalte): https://prnt.sc/19j5xdy

**Comment by norbertrost** [comment]
Wenn ich PM wäre müßte ich doch den Admin-Bereich sehen, oder? Tue ich aber nicht.

Da ich in Projekt 1 korrekterweise Schreibrechte habe (jedenfalls wenn ich deine Liste als Grundlage nehme), liegt das Problem demnach in der Darstellung von "Meine Anträge": dort müßte das Projekt auftauchen, tut es aber nicht.

Allerdings zeigt "meine Anträge" eh noch ein seltsames Verhalten, siehe #214

**Comment by philmuze** [comment]
@norbertrost um das zu checken brauch ich mal deine Logindaten für testing

**Comment by norbertrost** [comment]
Würde ich dir gerne geben, habe grade nur das Problem: Passwort zurücksetzen geht nicht.

**Comment by norbertrost** [comment]
Passwortänderung geht, aber der Client meldet das Gegenteil. Login-Daten: siehe Slack.

**Comment by philmuze** [comment]
Ich hatte createdProjects anstatt projectMemberships genutzt, ist gefixt

**Comment by j-schumann** [comment]
Aber unterscheidest du auch zwischen Bewerbern und Mitgliedern? Bewerber haben auch ein membershipObject nur mit anderer Rolle (applicant).

**Comment by philmuze** [comment]
Ohje nee noch nicht, dann verfeinere ich den Check.

**Comment by j-schumann** [comment]
Ja, du willst ja sicher Bewerbern auch eine Liste ausstehender Bewerbungen anzeigen die sie ggf zurückziehen können (DELETE)

**Comment by philmuze** [comment]
Ja gute Idee.
