### ISSUE TITLE
Mail-Templates anpassen

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#222]
So wie es aussieht hast du es auf dem Schirm aber wir können hier ja mal sammeln, was bezüglich der Email-Templates noch zu tun ist.

- [x] Title unterm Logo raus?
- [x] Type unten im Footer HackinPoliticsOnline - g fehlt
- [x] Impressum-Link

<img width="660" alt="Screenshot 2021-07-09 at 17 29 20" src="https://user-images.githubusercontent.com/1415444/125102466-99ef7980-e0db-11eb-9f26-035ea654e26b.png">

**Comment by j-schumann** [comment]
Impressumslink zeigt nun auf https://www.hacking-politics.de/impressum, könntest du mal einrichten.
