### ISSUE TITLE
Mitgliederverwaltung nicht übersetzbar

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#223]
Die Texte zur Mitgliederverwaltung sind nicht übersetzbar.
Deshalb steht da auch "Projektmitlieder"

**Comment by philmuze** [comment]
Wäre es nicht besser das mal einheitlich weiter in #204 zu sammeln?

**Comment by norbertrost** [comment]
Ach, das steht sogar shcon drin, dort als "Teamverwaltung". Closed.
