### ISSUE TITLE
Ungültige Projektanfrage an die API

### ISSUE THREAD

**Issue by j-schumann** [HackingPolitics/hp-frontend#227]
Habe hier folgendes im Log:

`[2021-07-10T00:23:58.768734+02:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Not Found" at /var/www/html/vendor/api-platform/core/src/EventListener/ReadListener.php line 116 
...
{"token":{"username":"anon.","authenticated":true,"roles":[]},"url":"/projects/null","ip":"2001:16b...","http_method":"GET","server":"backend.hacking-politics.de","referrer":"https://www.hacking-politics.de/","uid":"dc7338b"}
`

Unter welchen Umständen generiert der Client denn diese URL `/projects/null`? Wenn man ein nicht existierendes Projekt aufruft? Konnte es auf der leeren Plattform selbst nicht reproduzieren auf die Schnelle.

**Comment by philmuze** [comment]
Könnte mir vorstellen da fehlt ein Check. Bau ich ein.
