### ISSUE TITLE
WYSIWYG Editor checken und ersetzen

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#230]
- [ ] Projekt: Beschreibungstext  
  (project.description, API fertig, 2000 Zeichen + HTML)
- [ ] Projekt: Wirkung auf's Problem  
   (project.impact, in der API aktuell 2000 Zeichen + HTML)
- [ ] Projekt: Thema  
   (project.topic, in der API aktuell 1000 Zeichen einzeilig)
- [ ] Antrag: Einführung  
   (proposal.introduction, API fertig, 1000 Zeichen + HTML)
- [ ] Antrag: Handlungsauftrag  
   (proposal.actionMandate, API fertig, 5000 Zeichen + HTML)
- [ ] Antrag: Begründungsabsatz  
   (proposal.reasoning, API fertig, 20000 Zeichen + HTML)
- [ ] Antrag: Kommentar  
   (proposal.comment, API fertig, 5000 Zeichen + HTML)

![Screenshot 2021-07-12 at 14 36 26](https://user-images.githubusercontent.com/1415444/125294823-e974b600-e324-11eb-8882-cf639149368e.png)
![Screenshot 2021-07-12 at 14 36 32](https://user-images.githubusercontent.com/1415444/125294838-ebd71000-e324-11eb-877b-2899213ea3b2.png)

**Comment by philmuze** [comment]
@norbertrost als Checkliste sind die im Pflichtenheft definierten WYSIWYG Felder. Unten drunter die die grad im Client rin sind. Das Ziel habe ich jetzt nicht gefunden. Kannst du hier einfach nochmal kurz gegenchecken? Danke.

**Comment by norbertrost** [comment]
Erneute Analyse & Anpassung des Pflichtenhefts und folgende Erläuterungen:

- ja, die benannten Felder die zum ANTRAGSTEXT (=Schreibarbeit) gehören, sollen WYSIWYG-fähig sein
- Das was jetzt "Antragsziel"/ZIEL heißt, hatten wir in einer Diskussion mit dir und Tina ursprünglich mal "Beschreibungstext" genannt - ich tat mich damals schon schwer, weil es mir schwer fiel, "Thema" und "Beschreibung" gegenüber dem User zu differenzieren und dies vor allem im den Anfangs-Stadium zu tun, in dem das abgefragt werden sollte. In der späteren Arbeit mit dem Prototypen wurde aber sichtbar, dass die Abfrage eines ZIELES nützlich sein kann, weil die meisten User auch schon zu Beginn ihrer Denkarbeit ein Bild davon haben sollten, was als Ergebnis eines erfolgreichen Antrags an "Realitätsänderung" passieren soll. Daher sollte "Beschreibungstext" lieber durch ZIEL ersetzt werden. Das Pflichtenheft bildet das jetzt auch entsprechend ab.
- Sowohl bei ZIEL (Ex-Beschreibungstext) wie auch bei "Wirkung aufs Problem" würde ich aber auf HTML/WYSIWYG verzichten. Damit wären HTML/WYSIWYG-Elemente nur noch in der Schreibarbeit vorhanden. Finde ich gut.

**Comment by j-schumann** [comment]
Ergebnis summiert in #242, dort weiter.
