### ISSUE TITLE
Zeilenumbrüche erlauben

### ISSUE THREAD

**Issue by j-schumann** [HackingPolitics/hp-frontend#234]
Hallo Norbert,

du wolltest eigentlich das PH durchgehen und noch mal prüfen wo überall Zeilenumbrüche erlaubt sein sollen,
ich finde dazu aber nichts und die Angaben sind weiterhin nicht eindeutig, manchmal steht "Text", manchmal "Textfeld" und manchmal "Eingabefeld" da.

Folgender Stand ist aktuell in der API:

enthalten keine Felder die Umbrüche erlauben
- Council 
- Fraction 
- Category
- FederalState
- FractionDetails
- Partner
- ProjectMembership

mehrzeilig (description-Feld):
- Problem
- Argument
- CounterArgument
- Negation
- FractionInterest

Project:
- description + impact = HTML
- title + topic = einzeilig

Proposal:
- comment + introduction + actionMandate + reasoning = HTML
- title + sponsor + url = einzeilig

**Comment by norbertrost** [comment]
Ich bin jetzt nochmal über das Plichtenheft drüber und habe, wo uneindeutig, Eindeutigkeit herbeigeführt:
"Textfeld" steht für mehrzeilig, Zeilenumbrüche müssen erlaubt sein
"Eingabefeld" für einzeilig, Zeilenumbrüche sind nicht nötig

HTML dürfte im Grunde nur bei der abschließenden "Schreibarbeit" eine Rolle spielen, bei der Denkarbeit nicht.

**Comment by j-schumann** [comment]
Einführungstext beim Projekt kommt weg.

**Comment by j-schumann** [comment]
Ist das Absicht dass der Titel des Antrags mehrzeilig sein kann?

**Comment by norbertrost** [comment]
Nein, keine Absicht. Pflichtenheft angepasst.

**Comment by j-schumann** [comment]
API updated.
