### ISSUE TITLE
Darstellungsfehler: leere Bereiche am rechten und unteren Screen-Rand

### ISSUE THREAD

**Issue by norbertrost** [HackingPolitics/hp-frontend#296]
Seit kurzem gibt es am rechten Rand sowie am unteren Rand (zwischen Footer und Inhaltsbereich) graue leere Bereiche.
Dies tritt in ALLEN Screens auf, aber nur in einem Screen hat dieser Bereich eine "Funktion": nämlich in der Schreibarbeit. Dort wird der rechte graue Bereiche mit einem zusätzlichen Scrollbalken gefüllt, so dass zwei Scrollbalken vorhanden sind. Daher vermute ich, dass eine CSS-Option aus der Schreibarbeit hier in alle Screens "ausstrahlt".

Priorität: mittel

**Comment by philmuze** [comment]
@norbertrost bitte Screenshot und Browser ergänzen.

**Comment by norbertrost** [comment]
Ist tatsächlich grade nicht (mehr) reproduzierbar.
Chrome 92.0.4515.131 auf MacOS.
