### ISSUE TITLE
Send ProjectID in Socket

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#85]
Nun auch den Socketserver angepasst:
du kannst (solltest) beim joinGroup ein Callback übergeben (https://socket.io/docs/v3/emitting-events/#Acknowledgements), dort wird dann zukünftig ein Erfolgsstatus zurückkommen wenn der join geklappt hat, sonst forbidden (wenn du ein Projektteam joinen wolltest zu dem du keinen Zugriff hast) - gibt erstmal immer "ok" zurück wegen hartcodierter groupid
du solltest beim join als Parameter die Projekt-ID übergeben deren Team-Channel du joinen möchtest damit der Socketserver dich nicht in 5 Räume stecken muss wenn du 5 Teams angehörst und dir Nachrichten zu allen 5 Projekten schickt - funktionert erstmal weiter mit der hartcodierten groupid
beim Join bekommst du nicht mehr automatisch den aktuellen Dokumentenstand -> getDocument
Beim Join schickt er der Gruppe und auch dir die aktuelle Userliste, ich hab die aber im Firefox und Chrome fast nie bekommen, muss irgendeine Race-Condition sein, dass er das schon rausschickt bevor der Join fertig ist -> getUserList
die Userliste enthält jetzt nur noch id + username und nicht mehr die ganzen privaten Infos die die anderen nix angehen
lockedByUsername gibt nun korrekt auch den Usernamen zurück, ist aber eigentlich auch unnötig, die ID sollte doch reichen oder?
wir sollten lockField oder updateField entfernen, die funktionieren aktuell absolut identisch: damit nicht bei updateField der Lock-Status zurückgesetzt wird setze ich bei jedem update es auch gleich auf locked durch diesen User. Und lockFIeld löst auch nur das updateDocument an die Teammitglieder aus, die können das also sowieso nicht (einfach) unterscheiden

**Comment by j-schumann** [comment]
Komplettes Rework fällig mit Hocuspocus -> close
