### ISSUE TITLE
API Änderungen mitteilen

### ISSUE THREAD

**Issue by philmuze** [HackingPolitics/hp-frontend#90]

**Comment by j-schumann** [comment]
Api Stage wurde auf commit https://github.com/HackingPolitics/hp-backend/commit/eceda67abfbadbbe2edef147a108666a9154acc2 aktualisiert
Folgende Models wurden umbenannt und mit ihnen die entsprechenden Endpunkte:

* Parliament -> Council
* Faction* -> Fraction*

https://api-stage.hpo.vrok.de/ sollte also korrekt die verfügbaren Endpunkte anzeigen wobei aber die angegebenen Schemata sicher nicht immer korrekt sind, da ist noch ein Bug im Framework, dafür lieber auf die Unittests im Backend zurückgreifen: https://github.com/HackingPolitics/hp-backend/tree/main/tests/Api

**Comment by philmuze** [comment]
cc @TungSaysHelloToU

**Comment by j-schumann** [comment]
Die /projects können nun sortiert werden nach "id", "title", "updatedAt", "createdAt":
`/projects?order[createdAt]=desc`

**Comment by j-schumann** [comment]
Zum Project können nun Proposals angelegt und bearbeitet werden.

Zu einem Proposal können UsedArguments, UsedCounterArguments usw. hinzugefügt und wieder gelöscht werden (nicht jedoch bearbeitet). Diese Referenzierungen zwischen einem Antragsdokument und einem Element der Denkarbeit erhalten zusätzlich createdAt + createdBy für die Anzeige wer diese Verlinkung erstellt hat.

Stage ist nun auf https://github.com/HackingPolitics/hp-backend/commit/7535112dd74c7cf7d865b235f480df09ec5effac

**Comment by j-schumann** [comment]
Mit dem nächsten Update gehen folgende Änderungen live:

* Beim Abruf einer Liste der Stadträte kommen nur noch diejenigen mit active==true zurück, nur PROCESS_MANAGER kann nach active==false filtern
* Der Abruf eines einzelnen Rats mit active==false schlägt fehl für Nicht-PMs
* Beim Abruf eines (oder mehrerer) Stadträte kommen nur noch die Fraktionen mit active==true zurück
* Die Projektliste lässt sich nun nach Rat filtern (/projects/?council=[id] oder ?council=[@id])
* Beim Abruf einer Liste von Projekten oder eines einzelnen Projektes kommt nur die ID des Stadtrats mit zu dem das Projekt gehört
* Nur wenn man als Teammitglied ein Projekt abruft dann enthält der da angegebene Stadtrat weitere Details u.a. auch die inaktiven Fraktionen zu denen ggf. FractionDetails vorliegen. Daher: Für die Bearbeitung der Fraktionsinteressen etc immer den Council-Eintrag des Projekts verwenden um alle Fraktionen zu erhalten
* Nur noch ROLE_ADMIN kann Councils + Fractions löschen, das sollte aber auch vorerst nicht implementiert werden

**Comment by j-schumann** [comment]
Stage ist nun auf https://github.com/HackingPolitics/hp-backend/commit/d6821776779fcb602b3c4a07631287b2e02dd3bd
